// Copyright (c) 2025 Discovery Machine®, Inc.
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

#ifndef MUSIC_DTO_CPP_MUSIC_INCLUDE_MESSAGE_MUNITION_MUNITION_MESSAGE_H_
#define MUSIC_DTO_CPP_MUSIC_INCLUDE_MESSAGE_MUNITION_MUNITION_MESSAGE_H_

#include "enum/fuse_type.h"
#include "enum/warhead.h"
#include "message/entity_id.h"
#include "message/entity_type.h"
#include "message/event_id.h"
#include "message/location.h"
#include "message/music_message.h"
#include "message/vector.h"

namespace music {

class MunitionMessage : public MusicMessage {
  template <class T> friend class MunitionMessageBuilderTemplate;

 public:
  // Constructor
  MunitionMessage() : MusicMessage() { type_ = MusicMessageType::kFire; }
  // Validate
  void Validate() const;

  // Getters
  const EntityId &GetShooterId() const { return shooter_id_; }
  const std::optional<EntityId> &GetTargetId() const { return target_id_; }
  const EntityId &GetMunitionId() const { return munition_id_; }
  const MusicEventId &GetEventId() const { return event_id_; }
  const Vector &GetVelocity() const { return velocity_; }
  const Location &GetLocation() const { return location_; }
  const EntityType &GetMunition() const { return munition_; }
  const Warhead GetWarhead() const { return warhead_; }
  const FuseType GetFuse() const { return fuse_; }
  const int GetRate() const { return rate_; }
  const int GetQuantity() const { return quantity_; }

  // Setters
  void SetShooterId(const EntityId &shooter_id) { shooter_id_ = shooter_id; }
  void SetTargetId(const std::optional<EntityId> &target_id) { target_id_ = target_id; }
  void SetMunitionId(const EntityId &munition_id) { munition_id_ = munition_id; }
  void SetEventId(const MusicEventId &event_id) { event_id_ = event_id; }
  void SetVelocity(const Vector &velocity) { velocity_ = velocity; }
  void SetLocation(const Location &location) { location_ = location; }
  void SetMunition(const EntityType &munition) { munition_ = munition; }
  void SetWarhead(const Warhead &warhead) { warhead_ = warhead; }
  void SetFuse(const FuseType &fuse) { fuse_ = fuse; }
  void SetRate(int rate) { rate_ = rate; }
  void SetQuantity(int quantity) { quantity_ = quantity; }

  // JSON Keys
  inline static const std::string kShooterIdKey = "shooterID";
  inline static const std::string kTargetIdKey = "targetID";
  inline static const std::string kMunitionIdKey = "munitionID";
  inline static const std::string kEventIdKey = "eventID";
  inline static const std::string kVelocityKey = "velocity";
  inline static const std::string kLocationKey = "location";
  inline static const std::string kMunitionKey = "munition";
  inline static const std::string kWarheadKey = "warhead";
  inline static const std::string kFuseKey = "fuse";
  inline static const std::string kRateKey = "rate";
  inline static const std::string kQuantityKey = "quantity";

  // JSON serialization
  friend void to_json(nlohmann::json &j, const MunitionMessage &message);
  friend void from_json(const nlohmann::json &j, MunitionMessage &message);

  nlohmann::json ToJson() const {
    nlohmann::json j;
    to_json(j, *this);
    return j;
  }

  static MunitionMessage FromJson(const nlohmann::json &j) {
    MunitionMessage message;
    from_json(j, message);
    return message;
  }

  // Overload stream operator for easy testing and logging
  friend std::ostream &operator<<(std::ostream &os, const MunitionMessage &message) {
    os << message.ToString();
    return os;
  }

  std::string ToString() const { return "MunitionMessage: " + ToJson().dump(); }

 protected:
  // The entity identifier of the firing entity.
  EntityId shooter_id_{};

  // The entity identifier of the intended target. this field is optional.
  std::optional<EntityId> target_id_{};

  // The entity identifier of the fired munition if tracking data is required.
  EntityId munition_id_{};

  // An identifier generated by the firing entity that is used to associate this
  // fire with a corresponding detonation.
  MusicEventId event_id_{};

  // This field shall specify the velocity of the fired munition at the point
  // when the issuing simulation application intends the externally visible
  // effects of the launch (e.g. exhaust plume or muzzle blast) to first become
  // apparent.
  Vector velocity_{};

  // This field shall specify the location, in world coordinates, from which the
  // munition was launched.
  Location location_{};

  // The type of munition fired.
  EntityType munition_{};

  // The warhead shall be specified by a 16-bit enumeration.
  Warhead warhead_{Warhead::kUnset};

  // The fuse shall be specified by a 16-bit enumeration.
  FuseType fuse_{FuseType::kUnset};

  // The Rate shall represent the rounds per minute for the munition specified.
  int rate_{std::numeric_limits<int>::min()};

  // Quantity shall represent the number of rounds fired in the burst for the
  // munition specified.
  int quantity_{std::numeric_limits<int>::min()};
};

// Template builder class
template <class T> class MunitionMessageBuilderTemplate : public MessageBuilder<T> {
protected:
  std::shared_ptr<MunitionMessage> munition_message_;
  void SetBuiltMessage(std::shared_ptr<MusicMessage> new_message) {
    munition_message_ = std::static_pointer_cast<MunitionMessage>(new_message);
    MessageBuilder<T>::SetBuiltMessage(new_message);
  }

public:
  T &SetShooterId(const EntityId &shooter_id) {
    munition_message_->shooter_id_ = shooter_id;
    return static_cast<T &>(*this);
  }
  T &SetTargetId(const std::optional<EntityId> &target_id) {
    munition_message_->target_id_ = target_id;
    return static_cast<T &>(*this);
  }
  T &SetMunitionId(const EntityId &munition_id) {
    munition_message_->munition_id_ = munition_id;
    return static_cast<T &>(*this);
  }
  T &SetEventId(const MusicEventId &event_id) {
    munition_message_->event_id_ = event_id;
    return static_cast<T &>(*this);
  }
  T &SetVelocity(const Vector &velocity) {
    munition_message_->velocity_ = velocity;
    return static_cast<T &>(*this);
  }
  T &SetLocation(const Location &location) {
    munition_message_->location_ = location;
    return static_cast<T &>(*this);
  }
  T &SetMunition(const EntityType &munition) {
    munition_message_->munition_ = munition;
    return static_cast<T &>(*this);
  }
  T &SetWarhead(const Warhead &warhead) {
    munition_message_->warhead_ = warhead;
    return static_cast<T &>(*this);
  }
  T &SetFuse(const FuseType &fuse) {
    munition_message_->fuse_ = fuse;
    return static_cast<T &>(*this);
  }
  T &SetRate(int rate) {
    munition_message_->rate_ = rate;
    return static_cast<T &>(*this);
  }
  T &SetQuantity(int quantity) {
    munition_message_->quantity_ = quantity;
    return static_cast<T &>(*this);
  }
};

class MunitionMessageBuilder : public MunitionMessageBuilderTemplate<MunitionMessageBuilder> {
public:
  MunitionMessageBuilder() { SetBuiltMessage(std::make_shared<MunitionMessage>()); }

  MunitionMessage Build() { return *munition_message_; }
};

} // namespace music

#endif // MUSIC_DTO_CPP_MUSIC_INCLUDE_MESSAGE_MUNITION_MUNITION_MESSAGE_H_
